package-lock.json
src/pages/components/@shared/Input.tsx
src/pages/test/index.tsx
src/styles/globals.css
src/styles/scroll.module.css
tailwind.config.ts

공통 컴포넌트 인풋 추가
1. Input - 라벨, 에러 메시지, 포커스시 테두리 색이 변하는 기능 포함
2. SearchInout - 검색창 전용. 라벨 및 에러 메시지 없음
3. IconInput - 넣을 아이콘을 jsx 형식 컴포넌트로 만들어서 추가 가능, 핸들러 등록 가능
4. ScrollTextarea - 영역 크기 유지, 스크롤 가능
5. AutoTextArea - 영역 크기가 내용에 맞추어 늘어남, 제출 기능(임시)
자세한 사용법은 test 페이지에 적어두었습니다.
사용하시다 문제가 생기면 알려주세요!
tailwind관련 오류가 있어서 그것도 같이 수정했습니다!
_ 티켓번호, 티켓 링크(상세페이지 등등)

ZERO-28: 공통 컴포넌트 input 제작 + tailwind 오류 수정

---

src/components/auth/SignInForm.tsx
src/components/auth/SignUpForm.tsx
src/pages/signin/index.tsx

로그인 페이지 퍼블리싱
로그인 페이지 반응형 디자인
회원가입, 로그인 페이지 비밀번호 토글 기능 추가
제가 develop 브랜치를 pull해서 그런지 변경된 파일이 많이 뜨는데 맨 밑에 ZERO-49 커밋 두 개만 보시면 됩니다!
ZERO-49: https://fe08team4.atlassian.net/browse/ZERO-49

ZERO-49: 로그인 페이지 퍼블리싱

---

src/components/auth/SignInForm.tsx
src/components/auth/SignUpForm.tsx
src/libs/axios/axiosInstance.ts
src/pages/signin/index.tsx

회원가입 프로토타입을 만들었습니다. 
axiosInstance 추가
회원가입 기능 구현
회원가입 완료 시 로그인이  된 상태로 랜딩 페이지('/')로 이동
ZERO-55: https://fe08team4.atlassian.net/browse/ZERO-55

ZERO-55: 회원가입 프로토타입 제작

---

src/components/@shared/SideBar.tsx
src/pages/test/sidebar/index.tsx

- 사이드바 테스트 페이지 추가
- 사이드바 border 투명도 50 -> 10 수정
- 사이드바 테스트 페이지를 안만들었던것 같아서 추가했고 테스트 페이지 보시고 나중에 적용하시면 좋을것 같습니다
- navbar이전에 border투명도를 10으로 바꿨는데 사이드바도 동일한 투명도여야 할것 같아서 수정했습니다.
ZERO-29

ZERO-29 : 사이드바 테스트페이지 추가

---

src/components/auth/SignInForm.tsx
src/pages/signin/index.tsx

로그인 프로토타입
로그인 프로토타입입니다.
로그인이 성공하면 로그인 된 상태로 랜딩 페이지('/)로 이동합니다
ZERO-51: https://fe08team4.atlassian.net/browse/ZERO-51

ZERO-51: 로그인 프로토타입 제작

---

src/components/auth/Divider.tsx
src/components/auth/SignUpForm.tsx
src/pages/signup/index.tsx

회원가입 폼 입력값 유효성 검사
회원가입 폼 입력값 유효성 검사
입력값이 올바르지 않을 경우 버튼 비활성화
- 모든 입력값이 정상인 경우
- 하자 있을 때
ZERO-56: https://fe08team4.atlassian.net/browse/ZERO-56

ZERO-56: 회원가입 유효성 검사

---

src/components/team/CircleGraph.tsx
src/components/team/MemberBox.tsx
src/components/team/MemberList.tsx
src/components/team/Report.tsx
src/components/team/TaskBar.tsx
src/components/team/TaskList.tsx
src/components/team/TeamBanner.tsx
src/pages/[teamid]/index.tsx
src/pages/test/index.tsx
src/styles/globals.css
src/utils/calculateCircleProgress.ts

팀 페이지 퍼블리싱
원형 차트 컴포넌트 제작 (꽤 재활용 할만합니다)
팀 페이지 전체 퍼블리싱 완료
페이지 요구 디자인과 안 맞는 부분 있으면 알려주세요!
ZERO-82

ZERO-82:  팀페이지 퍼블리싱

---

src/components/@shared/NavBar.tsx

- 팀 이름에 드랍다운 기능 추가
- 드랍다운 기능 추가하였습니다.(이미지참고)
- 추후에 팀 이름과, 본인 프로필 이름 데이터 페칭 해보겠습니다!
- ZERO-25

ZERO-25 : NavBar 드랍다운 기능 추가

---

src/components/@shared/Button.tsx
src/pages/test/index.tsx

버튼 비활성화 스타일 추가
classname와 style에 자유롭게 속성 추가 가능
비활성화시 기본 색 지정
비활성화시 변경될 색을 직접 입력 가능
_집중 리뷰 부분 작성_
ZERO-84

ZERO-84: 버튼 컴포넌트 비활성화 스타일 추가

---

package-lock.json
package.json
src/api/myhistory/taskAPI.ts
src/components/@shared/SideBar.tsx
src/components/myhistory/MyTask.tsx
src/components/myhistory/mockdata.ts
src/hooks/myhistory/useDeleteTask.ts
src/hooks/myhistory/useTask.ts
src/types/myhistory/TaskType.ts

- dayjs적용
- 드롭다운에서 수정하기 버튼 눌렀을때 사이드바 활성화
- 드롭다운에서 삭제하기 버튼 눌렀을때 DELET API 연동
- 리팩토링
- 사이드바 수정
- 사이드바 관련해서 trigger를 옵셔널로 주고 isOpen과 onClose를 프롭으로 넘겨서 사용하는 곳에서 사이드바를 컨트롤 할수 있게 변경 하였습니다
- dayjs적용해서 포멧 변경
- 리팩토링 : 타입폴더를 만들어서 api 데이터 타입 지정했습니다
- 리팩토링 : 데이터 가져오는 api를 커스텀 훅으로 만들어서 myTask컴포넌트에서 사용하도록 하였습니다
- 드롭다운 수정하기, 삭제하기 버튼을 눌렀을때 발생되는 이벤트들 추가하였습니다
- 사이드바와 드롭다운이 서로 호환이 잘 안되는것 같아서 수정한 부분이 있습니다. 이상한 부분이 없는지 확인 부탁드려요!
- 그외 리팩토링도 함께 진행했습니다!
- 아직 수정하기 내부의 데이터 패칭과 내용은 완성못했는데 코드가 너무 길어질것 같아서 먼저 PR 올리고 추후에 사이드바 내용은 추가하도록 하겠습니다
- ZERO-48

ZERO-48 : 마이히스토리 페이지 수정

---

src/components/auth/SignInForm.tsx
src/components/auth/SignUpForm.tsx

로그인 유효성 검사
로그인 폼의 입력값에 대한 유효성 검사
모든 입력값이 정상이 아닐 때는 버튼 비활성화
- 아무것도 입력하지 않았을 때
- 이메일 또는 비밀번호를 잘못 입력했을 때
ZERO-52: https://fe08team4.atlassian.net/browse/ZERO-52

ZERO-52: 로그인 유효성 검사

---

src/components/@shared/NavBar.tsx

- pc, 테블릿, 모바일 별 반응형 수정
- navbar의 너비를 정해놓았었는데, full로 너비를 바꿔서 창 너비를 줄였을때 부드럽게 반응형으로 전환되도록 바꿨습니다
- ZERO-25

ZERO-25 : Navbar 반응형 수정

---

src/components/tasks/UI/Pagination.tsx
src/hooks/useViewportSize.tsx

> 1. 날짜 페이지네이션 구현
> 2. window 객체 에러 수정
1. 날짜 페이지네이션
　- 페이지네이션 버튼 클릭 시 전 날, 다음 날로 날짜 이동
　- 날짜 값 `DateContext`와 연동
2. `updateViewportSize` 훅에서 발생한 window 객체 에러 수정
---
---
> 없음
> ZERO-68

ZERO-68: 날짜 페이지네이션 구현 & useViewportSize 수정

---

src/components/@shared/MockUserData.ts
src/components/@shared/NavBar.tsx
src/hooks/mysetting/useUserData.ts
src/pages/_app.tsx
src/types/mysetting/settingData.ts

- 팀이름 드롭다운 api 연동
- mock데이터 테스트 완료
- 이름 눌렀을때 드롭다운 추가 
- 각 드롭다운을 통한 페이지 라우팅 추가
- 팀이름, 이름 부분 api 연동해서 userdata를 가지고 navbar와 연동되도록 만들었습니다
- 목데이터 가지고 테스트 했을떄는 문제 없으 작동하는것 확인 완료
- 이름 눌렀을때 각각의 페이지로 이동할수 있도록 라우팅 기능 추가했습니다
- 잘못된 부분이 있는지 확인 부탁드립니다.
- navbar 컴포넌트가 많이 지저분한데.. 추후에 리팩토링 하겠습니다ㅠ
- ZERO-102

ZERO-102 : Navbar API 연동

---

src/components/@shared/NavBar.tsx

navber 충돌 해결 과정에서 생긴 오류 수정
_집중 리뷰 부분 작성_
ZERO -114

ZERO -114 : nav bar 오류수정

---

src/components/auth/SignInForm.tsx
src/components/auth/SignUpForm.tsx
src/libs/axios/axiosInstance.ts
src/stores/useUserStore.ts

useUserStore 추가 (zustand)
axiosInstance 변경
회원가입, 로그인 코드 수정
- 회원가입이나 로그인을 하면 아래의 사진처럼 localStorage에 토큰과 유저 정보가 올라갑니다
ZERO-116

ZERO-116: 회원가입, 로그인 리팩토링

---

src/components/auth/ResetPasswordForm.tsx
src/pages/resetpassword/index.tsx

비밀번호 재설정 페이지 퍼블리싱
비밀번호 재설정 페이지 퍼블리싱 + 모달
- pc
- 태블릿
- 모바일
ZERO-58

ZERO-58: 비밀번호 재설정 페이지 퍼블리싱

---

next.config.mjs
package-lock.json
package.json
src/api/imageAPI.ts
src/api/team/teamAPI.ts
src/components/team/AddTeamModal.tsx
src/components/team/banner/DeleteTeamModal.tsx
src/components/team/banner/EditTeamModal.tsx
src/components/team/banner/TeamBanner.tsx
src/libs/axios/axiosInstance.ts
src/pages/[teamid]/index.tsx
src/pages/_app.tsx
src/stores/teamStore.ts

팀 추가, 수정, 삭제 기능 구현
1. axiosInstance 임시 수정
2. 팀 추가, 수정, 삭제 기능 구현 및 테스트 완료
3. zustand 사용하여 일부 리팩토링
4. 탠스택쿼리 데브툴스 설치
큰일이네요...
ZERO-96

ZERO-96 : 팀페이지 api연결 - 팀정보

---

src/components/addteam/AddTeamForm.tsx
src/components/addteam/ParticipateTeamForm.tsx
src/components/auth/ResetPasswordForm.tsx
src/components/auth/SignInForm.tsx
src/pages/addteam/index.tsx
src/pages/addteam/participate.tsx

팀 생성하기 페이지 퍼블리싱
팀 참여하기 페이지 퍼블리싱
- 모달 배경 색 변경
- 모달 훅 바뀐 이름 적용
- 팀 생성하기 페이지 퍼블리싱
모바일
태블릿
PC
- 팀 참여하기 페이지 퍼블리싱
모바일
태블릿
PC
ZERO-60

ZERO-60: 팀 생성하기 페이지 퍼블리싱

---

src/components/@shared/NavBar.tsx
src/components/mysetting/PasswordChange.tsx
src/components/mysetting/RemoveAccount.tsx

- navbar 모바일일때 팀 메뉴 트리거 로직 추가
- 공통모달 변경으로 인한 기존 모달 수정
- ZERO-125

ZERO-125 : Navbar 팀 메뉴 트리거 로직 추가

---

src/api/team/memberAPI.ts
src/components/@shared/NavBar.tsx
src/components/auth/ResetPasswordForm.tsx
src/components/auth/SignInForm.tsx
src/components/mysetting/PasswordChange.tsx
src/components/mysetting/RemoveAccount.tsx
src/components/tasks/UI/AddTaskListButton.tsx
src/components/team/AddTeamModal.tsx
src/components/team/banner/DeleteTeamModal.tsx
src/components/team/banner/EditTeamModal.tsx
src/components/team/banner/TeamBanner.tsx
src/components/team/member/ExileUserModal.tsx
src/components/team/member/GetUserDetailModal.tsx
src/components/team/member/InvitationModal.tsx
src/components/team/member/MemberBox.tsx
src/components/team/member/MemberList.tsx
src/components/team/taskList/AddTaskListModal.tsx
src/components/team/taskList/DeleteTaskListModal.tsx
src/components/team/taskList/EditTaskListModal.tsx
src/components/team/taskList/TaskBar.tsx
src/components/team/taskList/TaskList.tsx
src/libs/axios/axiosInstance.ts
src/pages/test/index.tsx

팀페이지 멤버삭제 API 추가
멤버 삭제 기능 추가
권한이 없거나 본인일 경우 삭제 막는 기능 추가
useModal관련 naming 수정
1. 멤버로 로그인했을 경우
2, 관리자로 로그인했을 경우
..
ZERO-113

ZERO-113 : 팀페이지 api연결 멤버삭제

---

src/api/addteam/participateTeamAPI.ts
src/components/addteam/AddTeamForm.tsx
src/components/addteam/ParticipateTeamForm.tsx

- 팀 생성하기 페이지 유효성 검사
- 팀 참여하기 페이지 유효성 검사
- 팀 생성하기 페이지 유효성 검사
- 팀 참여하기 페이지 유효성 검사
ZERO-64

ZERO-64: 팀 생성하기 및 참여하기 페이지 유효성 검사

---

src/pages/article/newarticle.tsx

- 게시글 작성하는 페이지 퍼블리싱
- ZERO-139

ZERO-139 : 게시글 쓰기 페이지 퍼블리싱

---

public/icons/x_white.svg
src/api/article/newarticleAPI.tsx
src/components/article/NewArticleImage.tsx
src/hooks/article/useNewArticle.tsx
src/pages/article/newarticle.tsx

- 게시글 작성하기 페이지 api 연동
- ZERO-140

ZERO-140 : 게시글 작성 api 연동

---

src/api/mysetting/inputAPI.ts
src/components/@shared/SideBar.tsx
src/components/article/CommentForm.tsx
src/components/article/NewArticleImage.tsx
src/components/auth/ResetPasswordForm.tsx
src/components/mysetting/inputTask.tsx
src/pages/article/newarticle.tsx

ZERO-140 [fix] : lint로인한 alert 모달 변경

---

src/components/team/banner/EditTeamModal.tsx

팀 이름 수정이 안 되는 버그 해결
버그도 잡고, 콘솔 무한에러도 해결했습니다
_집중 리뷰 부분 작성_
ZERO-143

ZERO-143 : 팀수정모달 수정불가 버그 해결

---

src/components/team/banner/EditTeamModal.tsx

초깃값이 제대로 설정되지 않는 버그 해결
초깃값이 제대로 설정되지 않는 버그 해결
.
ZERO-143

ZERO-143 : 팀수정모달 초깃값오류 해결

---

src/components/team/banner/DeleteTeamModal.tsx
src/components/team/banner/TeamBanner.tsx
src/components/team/member/GetUserDetailModal.tsx
src/components/team/member/MemberBox.tsx
src/components/team/member/MemberList.tsx
src/components/team/taskList/TaskList.tsx
src/styles/scroll.module.css

팀페이지 스크롤기능 추가 및 자잘한 디자인 수정
1. 스크롤 기능 추가
2. 삭제시 바로 refetch되도록 수정
3. 프로필 사진 잘 보이게 수정
---
삭제해도 뒤에 드롭다운 메뉴에는 남아있는 버그가 있습니다 ㅠ
ZERO-145

ZERO-145 : 팀페이지 스크롤기능 추가 및 자잘한 디자인 수정

---

package-lock.json
package.json
src/components/@shared/NavBar_Team.tsx
src/components/@shared/createTeamOption.tsx
src/components/team/banner/TeamBanner.tsx
src/components/team/member/GetUserDetailModal.tsx
src/components/team/member/ProfileImageModal.tsx
src/stores/teamStore.ts

- [] 기타
팀페이지 드롭다운메뉴 수정 및 멤버 프로필 모달 디자인 일부 변경
1. 드롭다운 모든 상황에서 같은 글자만 보여주게 변경
2. 프로필 모달 디자인 변경
기존:
변경:
3. 프로필 사진 크게 보기 기능
_집중 리뷰 부분 작성_

ZERO-146 : 팀페이지 드롭다운메뉴 연동

---

src/api/tasks/taskListAPI.ts
src/components/@shared/LoadingSpinner.tsx
src/components/team/taskList/DeleteTaskListModal.tsx
src/components/team/taskList/EditTaskListModal.tsx
src/components/team/taskList/TaskBar.tsx
src/components/team/taskList/TaskList.tsx
src/hooks/useDragAndDrop.ts
src/hooks/useTaskLiskModals.ts

팀페이지 drag and drop 기능 구현
1. 드래그앤 드롭 기능 구현 (+ 드롭다운 컴포넌트 부모 요소로 끌어올림)
2. API함수 관련 수정
3. 린트 관련 수정
4. 리팩토링을 위한 밑작업
---
---
컴포넌트 하나가 너무 길어져서 분리하려고 밑작업만 해두었습니다!
잘 안 될 것 같아서 잠깐 물러섭니다..
ZERO-134

ZERO-134 : 팀페이지 drag and drop

---

src/components/@shared/NavBar.tsx
src/components/@shared/NavBar_Team.tsx
src/hooks/mysetting/useUserData.ts
src/pages/oauth/google.tsx
src/pages/oauth/kakao.tsx
src/pages/signin/index.tsx
src/pages/signup/index.tsx
src/stores/useUserStore.ts

간편 로그인 시 닉네임 설정 페이지 네비바 설정
로그인, 회원가입 리다이렉트 설정
간편 로그인 시 닉네임 설정 페이지에서 로고만 있는 네비바로 설정
로그인 상태일 때 로그인, 회원가입 페이지에 들어가면 팀 리스트 페이지로 리다이렉트
추가로 더 개선할 사항이 있음
ZERO-149

ZERO-149: 유저 기능 관련 페이지 개선

---

src/components/auth/SignInForm.tsx
src/components/auth/SignUpForm.tsx
src/pages/_app.tsx

- 로컬 스토리지 날리면 로그인 페이지로 이동
- 회원가입, 로그인 유효성 검사 수정
- 토큰 만료 등의 이유로 로컬 스토리지가 지워지면 로그인 페이지로 리다이렉트
- 회원가입 이메일 50자 이내로 제한, 이메일 형식 엄격하게 수정(영문, 숫자, 특수문자 반드시 포함 이외의 문자 X)
- 로그인 이메일 형식 엄격하게 수정
ZERO-154

ZERO-154:  유저 기능 1차 QA

---

package-lock.json
package.json
src/components/mysetting/PasswordInput.tsx
src/components/mysetting/RemoveAccount.tsx
src/components/mysetting/ShareModal.tsx
src/components/mysetting/inputTask.tsx

- 회원 탈퇴 기능 디버깅
- 이름, 이메일 첫 랜더링때 보이도록 수정
- 이름, 프로필이미지 수정시 완료 모달
- 기존 회원 탈퇴시 DELET API가 보내지기 전에 로컬스토리지의 데이터를 삭제함으로 정상적으로 API가 전송되지 않음
-> 비동기로 API를 날리고 완료 된후에 로컬 스토리지 삭제하도록 수정
- 이름, 이메일 useEffect를 통해서 첫 랜더링때 보이도록 수정
- 이름, 프로필 변경하면 완료 모달 띄움
---
---
- ZERO-155

ZERO-155 : 계정설정페이지 1차 QA 피드백 반영

---

src/components/@shared/Modal.tsx
src/components/team/taskList/TaskList.tsx
src/styles/globals.css

모달이 열릴 때 생기는 이슈 수정
1. 모달이 열릴 때 스크롤이 없어지며 페이지가 흔들리는 현상 개선
2. 전체 페이지 기본 스크롤 디자인 적용
3. 모달 외부로 드래그시 모달이 꺼지는 현상 개선
---
---
제 페이지가 모달을 많이 써서 제껀줄 착각하고 수정했슴다..
ZERO-152

ZERO-152 : 공통 - 모달 스크롤

---

src/components/myhistory/MyTask.tsx

- 랜더링 오류 수정
- 히스토리 설정 드롭다운 삭제
- tasks를 가져올때 배열인지 검사하고 가져올수 있도록 검사하는 로직 추가, 검사이후 정상인지 판단되면 데이터를 가져옴
- 설정 드롭다운 삭제 : api를 보면 수정하거나 삭제할수 있는 api가 없음 get api만 있어서 우선 보여주는 용도로만 사용된다고 생각됩니다.
---
---
- ZERO-157

ZERO-157 : 마이히스토리 페이지 랜더링 오류 수정

---

src/components/mysetting/inputTask.tsx

- 마이세팅 페이지 닉네임 글자 제한
- 마이세팅 페이지 닉네임 글자 10글자 내외로 제한
---
---
_집중 리뷰 부분 작성_
- ZEOR-155

ZERO-155 : 닉네임 변경 글자 제한

---

next.config.mjs
src/components/article/ArrayDropdown.tsx
src/components/article/ArticleCard.tsx
src/components/article/BestCard.tsx
src/components/article/CommentList.tsx
src/components/article/DetailCard.tsx
src/components/article/NewArticleImage.tsx
src/pages/article/edit/[articleId].tsx
src/pages/article/index.tsx
src/pages/article/newarticle.tsx

- best카드 디자인 수정
- 댓글 프로필 이미지없으면 오류나는 버그 수정
- 게시글 제목 50자 제한
- 게시글 검색시 쿼리 파라미터 적용
- 인기순 / 최신순 쿼리 파라미터 적용
- 베스트 카드 제목 길어져도 디자인 꺠지지 않도록 수정
- 게시글에 댓글작성자의 프로필이 없으면 오류발생 -> Image 컴포넌트의 null일때의 기본값 지정해줌
- 게시글 제목 50자 제한
- 게시글 검색, 인기순, 최신순 쿼리 파라미터 적용
---
- 베스트 카드 디자인 수정
- 게시글 작성시 제목 50자 제한
- 게시글 쿼리 파라미터 적용
---
- ZERO-158

ZERO-158 : 게시판 페이지 QA1차 디버깅

---

src/components/article/ArticleCard.tsx
src/components/article/BestCard.tsx
src/components/article/CommentList.tsx
src/components/article/DetailCard.tsx
src/components/article/Heart.tsx

- 좋아요 기능 로직 수정
- 게시글 본인만 수정/삭제 가능하도록 수정
- 댓글 보인 댓글만 수정/삭제 가능하도록 수정
- 게시글 페이지 이미지 위치 수정
- 좋아요 기능을 게시판 메인 페이지에서 누를 수 있도록 초기에는 만들어놨는데, 게시글 리스트 페이지에서는 좋아요를 직접적으로 건드릴수 있는 api가 존재하지 않음 -> 게시글 상세페이지에서 좋아요 누를수 있도록 수정
- 게시글 권한있는 본인만 수정삭제하도록
- 댓글 권한있는 본인만 수정삭제하도록 
---
게시글 페이지 이미지 위치 수정
---
- ZERO-158

ZERO-158 : 좋아요 기능 로직 수정

---

src/components/tasks/TaskDate.tsx
src/components/tasks/TaskList.tsx
src/pages/[teamid]/tasks.tsx

1. 리스트 페이지 전환 시 로딩스피너 적용
2. 리스트 페이지 버그 수정
> ### Fix
- 팀 변경 시 변경된 팀의 taskList가 업데이트되지 않는 버그
- 초기 페이지 로드 시 페이지네이션이 적용되지 않는 버그
---
> X
> ZERO-161

ZERO-161: 리스트 페이지 로딩 스피너 적용 & 업데이트 관련 버그 수정

---

src/components/tasks/TaskCard.tsx
src/components/tasks/UI/TaskEditDropdown.tsx
src/components/tasks/UI/modal/DeleteRecurringModal.tsx
src/components/tasks/UI/modal/DeleteTaskModal.tsx

- **할 일 일괄 삭제 기능 추가**
- **할 일 카드 드롭다운 수정**
- **삭제 모달 안내 문구 수정**
- **할 일 일괄 삭제 기능**
　- 할 일 선택 삭제 모달과 분리
---
> **드롭다운**
>  **할 일 선택 삭제 모달**
> **할 일 일괄 삭제 모달**
---
> 놓치고 있던 기본 기능을 추가했습니다.
> ZERO-167

ZERO-167: 할 일 일괄 삭제 기능 추가 & 삭제 안내 문구 변경

---

src/components/@shared/animation/IconSparkleMotion.tsx
src/components/home/Content.tsx
src/styles/sparkle.module.css

ZERO-176: css 파일 경로 에러 수정

---

package-lock.json
package.json
src/components/myhistory/Contributions.tsx
src/pages/myhistory/[id].tsx
src/styles/scroll.module.css

- 잔디기능 가로로 수정
- 너비가 줄어들었을때 스크롤 생성(테일윈드 스크롤바 히든 추가설치)
---
---
- ZERO-174

ZERO-174  : 잔디 가로로 수정

---

src/components/@shared/NavBar.tsx
src/components/@shared/NavBar_Team.tsx
src/components/@shared/ProfileImageInput.tsx
src/components/article/ArticleCard.tsx
src/components/article/BestCard.tsx
src/components/article/Skeleton.tsx/ArticleCardSkeletonCard.tsx
src/components/article/Skeleton.tsx/ArticleSkeletonUI.tsx
src/components/article/Skeleton.tsx/BestCardSkeletonCard.tsx
src/components/article/Skeleton.tsx/BestSkeletonUI.tsx
src/components/mysetting/inputTask.tsx
src/pages/article/index.tsx
src/styles/globals.css

- 계정 설정 페이지 토스트 오류 수정
- 프로필 이미지 가로로 긴 이미지 넣을때 깨지는 부분 수정
- 게시판 게시글 이미지 꺠짐 수정
- 스켈레톤 ui 추가
- 자유게시판 -> 커뮤니티로 변경, ?아이콘 추가
---
>수정후
---
- 영상 보시면 스켈레톤 UI가 위로 올라갔다가 내려오는데 이 부분은 추후 해결하도록 하겠습니다..!ㅠ
- ZERO-181

ZERO-181 : 게시판 페이지 버그 수정 및 리팩토링

---

README.md

- README 초안 작성
- App 배포 후 재수정하겠습니다.

App 배포 전 README 작성
